data_path : './dataset/pungency.xlsx'
test_size : 0.2
predictor_cfgs :
  label : 'Sensory score'
  problem_type : 'regression'
  eval_metric : 'mean_squared_error'
  path : './result/pungency'
  verbosity : 2
train_cfgs : 
  hyperparameter_tune_kwargs : 
    num_trials : 500
    scheduler : 'local'
    searcher : 'auto'
  num_bag_folds : 3
metrics : ['r2', 'rmse']
sort_by : 'r2'